/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.dbarcarcel.vista;

import org.dbarcarcel.controlador.ControlProveedor;
import org.dbarcarcel.modelo.Proveedor;

/**
 *
 * @author informatica
 */
public class ActualizarProveedor extends javax.swing.JInternalFrame {
public static ControlProveedor controladorActualizar = ControlProveedor.getInstancia();

    /**
     * Creates new form ActualizarProveedor
     */
    public ActualizarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNuevotTelefonoMedico = new javax.swing.JLabel();
        txtNuevoTelefonoMedico = new javax.swing.JTextField();
        lblNuevoEmail = new javax.swing.JLabel();
        txtNuevoEmail = new javax.swing.JTextField();
        lblNuevaDireccion = new javax.swing.JLabel();
        txtNuevaDireccion = new javax.swing.JTextField();
        lblAntiguoMedicoActualizar = new javax.swing.JLabel();
        txtIdAntiguo = new javax.swing.JTextField();
        botonActualizarMedico = new javax.swing.JButton();
        lblNuevoNombreDoctor = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();

        lblNuevotTelefonoMedico.setText("Telefono ");

        lblNuevoEmail.setText("Email");

        lblNuevaDireccion.setText("Dirección");

        lblAntiguoMedicoActualizar.setText("ID  ");

        botonActualizarMedico.setText("Actualizar");
        botonActualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarMedicoActionPerformed(evt);
            }
        });

        lblNuevoNombreDoctor.setText("Nombre ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevoNombreDoctor)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNuevoEmail)
                            .addComponent(txtNuevoTelefonoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNuevotTelefonoMedico)
                            .addComponent(lblAntiguoMedicoActualizar)
                            .addComponent(lblNuevaDireccion)
                            .addComponent(txtNuevaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(botonActualizarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAntiguoMedicoActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNuevoNombreDoctor)
                        .addGap(16, 16, 16)
                        .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNuevotTelefonoMedico)
                        .addGap(18, 18, 18)
                        .addComponent(txtNuevoTelefonoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblNuevaDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNuevaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNuevoEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(txtNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonActualizarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarMedicoActionPerformed
        Proveedor provee = new Proveedor();
        provee.setId(Integer.parseInt(txtIdAntiguo.getText()));
        provee.setProveedor(txtNuevoNombre.getText());
        provee.setTelefono(Integer.parseInt(txtNuevoTelefonoMedico.getText()));
        provee.setDireccion(txtNuevaDireccion.getText());
        provee.setEmail(txtNuevoEmail.getText());

        controladorActualizar.actualizarProveedor(provee);
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarMedico;
    private javax.swing.JLabel lblAntiguoMedicoActualizar;
    private javax.swing.JLabel lblNuevaDireccion;
    private javax.swing.JLabel lblNuevoEmail;
    private javax.swing.JLabel lblNuevoNombreDoctor;
    private javax.swing.JLabel lblNuevotTelefonoMedico;
    private javax.swing.JTextField txtIdAntiguo;
    private javax.swing.JTextField txtNuevaDireccion;
    private javax.swing.JTextField txtNuevoEmail;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoTelefonoMedico;
    // End of variables declaration//GEN-END:variables
}
