/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.dbarcarcel.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.dbarcarcel.controlador.ControlCompra;
import org.dbarcarcel.modelo.Compra;
import org.dbarcarcel.modelo.Producto;
import static org.dbarcarcel.vista.VerProductos.controlador;

/**
 *
 * @author dako
 */
public class VerCompra extends javax.swing.JInternalFrame {
public static ControlCompra controlador = ControlCompra.getInstancia();
    /**
     * Creates new form VerCompra
     */
    public VerCompra() {
        initComponents();
        mostrarDatos();
    }
    public void mostrarDatos(){
       String [] encabezados = {"ID","Fehca","ID Usuario","ID Producto","Estado"};
       int cantidadDeProductos = controlador.cantidadDeCompras();

       DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeProductos);
       jTable1.setModel(cabeceraDeTabla);
       TableModel listaDeDatos = jTable1.getModel();

       for(int i=0; i<cantidadDeProductos; i++){
       Compra compra = controlador.listaDeCompras().get(i);
       listaDeDatos.setValueAt(compra.getId(), i, 0);
       listaDeDatos.setValueAt(compra.getFecha(), i, 1);
       listaDeDatos.setValueAt(compra.getId_usuarios(), i, 2);
       listaDeDatos.setValueAt(compra.getId_producto(), i, 3);
       listaDeDatos.setValueAt(compra.isEstado_activo(), i, 4);
      
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID compra", "Fecha", "ID Usuario", "ID Producto", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
