/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.dbarcarcel.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.dbarcarcel.controlador.ControlProveedor;
import org.dbarcarcel.modelo.Proveedor;

/**
 *
 * @author informatica
 */
public class VerProveedores extends javax.swing.JInternalFrame {
public static ControlProveedor controladorProveedor = ControlProveedor.getInstancia();

    /**
     * Creates new form VerProveedores
     */
    public VerProveedores() {
        initComponents();
        mostrarDatos();
    }
    
public void mostrarDatos(){
       String [] encabezados = {"ID Proveedor","Proveedor","Telefono","Direccion","email"};
       int cantidadDeProveedores = controladorProveedor.cantidadDeProveedores();

       DefaultTableModel cabeceraDeTabla = new DefaultTableModel(encabezados, cantidadDeProveedores);
       tablaProveedor.setModel(cabeceraDeTabla);
       TableModel listaDeDatos = tablaProveedor.getModel();

       for(int i=0; i<cantidadDeProveedores; i++){
       Proveedor proveedor = controladorProveedor.listaDeProveedor().get(i);
       listaDeDatos.setValueAt(proveedor.getId(), i, 0);
       listaDeDatos.setValueAt(proveedor.getProveedor(), i, 1);
       listaDeDatos.setValueAt(proveedor.getTelefono(), i, 2);
       listaDeDatos.setValueAt(proveedor.getDireccion(), i, 3);
       listaDeDatos.setValueAt(proveedor.getEmail(), i, 4);
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID ", "Proveedor", "Telefono", "Direccion", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedor;
    // End of variables declaration//GEN-END:variables
}
